### ISSUE TITLE
Curious if you test this on a non-git folder?

### ISSUE THREAD

**Issue by niftylettuce** [cabinjs/parse-app-info#2]
I'm just wondering if we should add error-handling or a try/catch wrapper.

**Comment by pke** [comment]
I tested it. The promise rejects.
I wonder what would be the expected behaviour from a users perspective?
In case no commits have been performed in the project should the `hash` and `tag` be empty strings?

**Comment by niftylettuce** [comment]
@pke Can you make it so that it _only_ adds the properties (otherwise omits them) if the promise rejects?  So you would wrap try/catch here https://github.com/pke/parse-app-info/blob/master/index.js#L26-L29 I think.

**Comment by pke** [comment]
you mean add them *only* if the promise does *not* reject?

**Comment by niftylettuce** [comment]
correct @pke

**Comment by niftylettuce** [comment]
I'll version bump and publish, one moment!
