### ISSUE TITLE
fix: istanbul branch coverage 0%

### ISSUE THREAD

**Issue by niftylettuce** [cabinjs/parse-app-info#4]
I don't think the `/* istanbul ignore if */` is working?

ref:
- https://github.com/pke/parse-app-info/blob/master/index.js#L17
- https://travis-ci.com/pke/parse-app-info/jobs/150161526#L483
- https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md

**Comment by pke** [comment]
I'll fix that later with proper mocks.
