### ISSUE TITLE
Can we move this to the @cabinjs org?

### ISSUE THREAD

**Issue by niftylettuce** [cabinjs/parse-app-info#7]
https://github.com/cabinjs

I can make you an owner of the repo there once you move it and also add you to the CabinJS team on GitHub

**Comment by pke** [comment]
as you wish. You can be the owner too and add me as member.

**Comment by niftylettuce** [comment]
Ok cool, whenever you transfer it let me know!  I've already added you on a Team for Cabin and once this is moved I'll add you there.  Thank you.

**Comment by pke** [comment]
Can't transfer because of missing permissions on cabinjs

**Comment by niftylettuce** [comment]
@pke you should have access now

**Comment by pke** [comment]
Done
